version: '3.8'
services:
  localhost:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aspyrio_app_db
    ports:
      - "5432:5432"
